# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.1 on Thu Dec 06 09:23:21 2007

import wx
import GFX

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class cDummyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: cDummyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: cDummyFrame.__set_properties
        self.SetTitle(_("RToolDS"))
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(GFX.catalog ["GFX_Icon"].getBitmap())
        self.SetIcon(_icon)
        self.SetSize((400, 300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: cDummyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade
        self.SetPosition((9999,9999))

# end of class cDummyFrame


