#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1 on Wed Nov 29 09:19:40 2006

import wx
from MyFrame import MyFrame

import sys
import os
import MyConfig
import AdvancedSplash as AS

class MyApp( wx.App ):
    def OnInit( self ):
        wx.InitAllImageHandlers()
#        m_MainFrame = MySaveGameDlg.MySaveGameDlg (None, -1)
#        self.SetTopWindow (m_MainFrame)
#        m_MainFrame.Show()
        
        m_MainFrame = MyFrame( None, -1, "" )
        self.SetTopWindow( m_MainFrame )
        m_MainFrame.Show()
        if MyConfig.ShowSplash == 1:
            pass
            bitm = wx.Bitmap( "logo.png" )
            AS.AdvancedSplash( m_MainFrame, 
                                             bitmap=bitm, 
                                             timeout=5000, 
                                             extrastyle=AS.AS_CENTER_ON_SCREEN|AS.AS_TIMEOUT|AS.AS_SHADOW_BITMAP, 
                                             shadowcolour=wx.Colour( 255, 255, 0 )
                                             )
        return 1

# end of class MyApp

if __name__ == "__main__":
    ConfigFileName = os.path.join ( os.path.realpath( os.path.dirname( sys.argv[0] ) ), "RToolDS.cfg" )
    MyConfig.Load ( ConfigFileName )
    app = MyApp( 0 )
    app.MainLoop()
    MyConfig.Save ( ConfigFileName )