# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.1 on Fri Nov 09 15:39:15 2007

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class cProgressFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: cProgressFrame.__init__
        kwds["style"] = wx.CAPTION|wx.FRAME_FLOAT_ON_PARENT
        wx.Frame.__init__(self, *args, **kwds)
        self.ProgressFramePanel = wx.Panel(self, -1)
        self.Proccessing_Text = wx.StaticText(self.ProgressFramePanel, -1, _("Processing"), style=wx.ALIGN_CENTRE|wx.ST_NO_AUTORESIZE)
        self.Guage1 = wx.Gauge(self.ProgressFramePanel, -1, 10, style=wx.GA_HORIZONTAL|wx.GA_SMOOTH)
        self.Guage2 = wx.Gauge(self.ProgressFramePanel, -1, 10, style=wx.GA_HORIZONTAL|wx.GA_SMOOTH)
        self.Cancel_Button = wx.Button(self.ProgressFramePanel, wx.ID_CANCEL, _("&Cancel"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.On_Cancel, id=wx.ID_CANCEL)
        # end wxGlade
        
        self.Abort = False

    def __set_properties(self):
        # begin wxGlade: cProgressFrame.__set_properties
        self.SetTitle(_("Processing"))
        self.Guage1.SetMinSize((400, 25))
        self.Guage2.SetMinSize((400, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: cProgressFrame.__do_layout
        ProgressFrame_Sizer1 = wx.BoxSizer(wx.VERTICAL)
        ProgressFrame_Sizer2 = wx.BoxSizer(wx.VERTICAL)
        ProgressFrame_Sizer3 = wx.BoxSizer(wx.VERTICAL)
        ProgressFrame_Sizer3.Add(self.Proccessing_Text, 0, wx.ALL|wx.EXPAND, 10)
        ProgressFrame_Sizer3.Add(self.Guage1, 0, wx.ALL|wx.EXPAND, 5)
        ProgressFrame_Sizer3.Add(self.Guage2, 0, wx.ALL|wx.EXPAND, 5)
        ProgressFrame_Sizer3.Add(self.Cancel_Button, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        self.ProgressFramePanel.SetSizer(ProgressFrame_Sizer3)
        ProgressFrame_Sizer2.Add(self.ProgressFramePanel, 1, wx.EXPAND, 0)
        ProgressFrame_Sizer1.Add(ProgressFrame_Sizer2, 1, wx.EXPAND, 0)
        self.SetSizer(ProgressFrame_Sizer1)
        ProgressFrame_Sizer1.Fit(self)
        self.Layout()
        # end wxGlade

    def On_Cancel(self, event): # wxGlade: cProgressFrame.<event_handler>
        self.Abort = True

    def DisableGuage2 ( self ):
        self.Guage2.Hide()
        self.Fit()
        
# end of class cProgressFrame


