# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1cvs on Tue Dec 12 10:26:46 2006 from C:\Documents and Settings\rj\workspace\RToolDS\RToolDS.wxg

import wx

# begin wxGlade: dependencies
# end wxGlade

class MyAboutDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyAboutDialog.__init__
        kwds["style"] = wx.CAPTION
        wx.Dialog.__init__(self, *args, **kwds)
        self.bitmap_1 = wx.StaticBitmap(self, -1, wx.Bitmap("About.png", wx.BITMAP_TYPE_ANY))
        self.m_TitleText = wx.StaticText(self, -1, "label_3", style=wx.ALIGN_CENTRE)
        self.m_AboutText = wx.StaticText(self, -1, "Arg")
        self.static_line_1 = wx.StaticLine(self, -1)
        self.m_About_OK_Ctrl = wx.Button(self, -1, "OK")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnOK, self.m_About_OK_Ctrl)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyAboutDialog.__set_properties
        self.SetTitle("About RToolDS")
        self.SetSize((431, 388))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyAboutDialog.__do_layout
        grid_sizer_10 = wx.FlexGridSizer(4, 1, 0, 0)
        grid_sizer_10.Add(self.bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        grid_sizer_10.Add(self.m_TitleText, 0, wx.ALL|wx.EXPAND, 5)
        grid_sizer_10.Add(self.m_AboutText, 0, wx.LEFT|wx.RIGHT|wx.TOP|wx.EXPAND, 5)
        grid_sizer_10.Add(self.static_line_1, 0, wx.EXPAND, 0)
        grid_sizer_10.Add(self.m_About_OK_Ctrl, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        self.SetSizer(grid_sizer_10)
        grid_sizer_10.AddGrowableRow(2)
        grid_sizer_10.AddGrowableCol(0)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnOK(self, event): # wxGlade: MyAboutDialog.<event_handler>
        self.Close()
        event.Skip()

# end of class MyAboutDialog


