# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1cvs on Thu Jan 18 11:17:45 2007 from C:\Documents and Settings\rj\workspace\RToolDS\RToolDS.wxg

import wx
import MyConfig

# begin wxGlade: dependencies
# end wxGlade

class MyBadZipDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyBadZipDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.m_BadZipListBox = wx.ListBox(self, -1, choices=[], style=wx.LB_SINGLE)
        self.m_BadZip_OK_Btn = wx.Button(self, -1, "OK")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnOK, self.m_BadZip_OK_Btn)
        # end wxGlade
        self.BadZips = MyConfig.BadZips
        self.__LocalInit()


    def __set_properties(self):
        # begin wxGlade: MyBadZipDialog.__set_properties
        self.SetTitle("Bad Zip Files")
        self.SetSize((400, 300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyBadZipDialog.__do_layout
        sizer_7_copy_copy_copy = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_3_copy_copy_copy_copy = wx.FlexGridSizer(1, 3, 0, 0)
        sizer_7_copy_copy_copy.Add(self.m_BadZipListBox, 0, wx.EXPAND, 0)
        grid_sizer_3_copy_copy_copy_copy.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_3_copy_copy_copy_copy.Add(self.m_BadZip_OK_Btn, 0, wx.TOP|wx.BOTTOM, 5)
        grid_sizer_3_copy_copy_copy_copy.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_3_copy_copy_copy_copy.AddGrowableCol(0)
        grid_sizer_3_copy_copy_copy_copy.AddGrowableCol(2)
        sizer_7_copy_copy_copy.Add(grid_sizer_3_copy_copy_copy_copy, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_7_copy_copy_copy)
        sizer_7_copy_copy_copy.AddGrowableRow(0)
        sizer_7_copy_copy_copy.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def __LocalInit(self):
        self.m_BadZipListBox.AppendItems(self.BadZips)
        
    def OnOK(self, event): # wxGlade: MyBadZipDialog.<event_handler>
        self.Close()
        event.Skip()

# end of class MyBadZipDialog


