# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1cvs on Sat Dec 09 16:17:41 2006 from C:\Documents and Settings\rj\workspace\RToolDS\RToolDS.wxg

import wx
import MyConfig

# begin wxGlade: dependencies
# end wxGlade

class MyDuplicateDlg(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDuplicateDlg.__init__
        kwds["style"] = wx.CAPTION|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.m_DuplicateListBox = wx.ListBox(self, -1, choices=[], style=wx.LB_SINGLE)
        self.m_DuplcateGame_OK_Btn = wx.Button(self, -1, "OK")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnOptionsOK, self.m_DuplcateGame_OK_Btn)
        # end wxGlade
        self.DuplicateFiles = MyConfig.DuplicateFiles
        self.__LocalInit()

    def __set_properties(self):
        # begin wxGlade: MyDuplicateDlg.__set_properties
        self.SetTitle("Duplicate Files Found...")
        self.SetSize((400, 300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDuplicateDlg.__do_layout
        sizer_7_copy = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_3_copy_copy = wx.FlexGridSizer(1, 3, 0, 0)
        sizer_7_copy.Add(self.m_DuplicateListBox, 0, wx.EXPAND, 0)
        grid_sizer_3_copy_copy.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_3_copy_copy.Add(self.m_DuplcateGame_OK_Btn, 0, wx.TOP|wx.BOTTOM, 5)
        grid_sizer_3_copy_copy.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_3_copy_copy.AddGrowableCol(0)
        grid_sizer_3_copy_copy.AddGrowableCol(2)
        sizer_7_copy.Add(grid_sizer_3_copy_copy, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_7_copy)
        sizer_7_copy.AddGrowableRow(0)
        sizer_7_copy.AddGrowableCol(0)
        self.Layout()
        self.Centre()
        # end wxGlade

    def __LocalInit(self):
#        for File in self.GetParent().DuplicateFiles:
#        self.m_DuplicateListBox.Delete(0)
        self.m_DuplicateListBox.AppendItems(self.DuplicateFiles)
        
    def OnOptionsOK(self, event): # wxGlade: MyDuplicateDlg.<event_handler>
        self.Close()
        event.Skip()

# end of class MyDuplicateDlg


