# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1cvs on Tue Dec 19 08:20:58 2006 from C:\Documents and Settings\rj\workspace\RToolDS\RToolDS.wxg

import wx
import MyConfig

# begin wxGlade: dependencies
# end wxGlade

class MyEditGenreDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyEditGenreDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.m_EditGenre_Text = wx.StaticText(self, -1, "label_3")
        self.m_EditGenreComboBox = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN)
        self.m_EditGenre_OK_Btn = wx.Button(self, -1, "OK")
        self.m_EditGenre_Cancel_Btn = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT, self.OnEditGenreText, self.m_EditGenreComboBox)
        self.Bind(wx.EVT_COMBOBOX, self.OnEditGenreCombo, self.m_EditGenreComboBox)
        self.Bind(wx.EVT_BUTTON, self.OnGenreOK, self.m_EditGenre_OK_Btn)
        self.Bind(wx.EVT_BUTTON, self.OnGenreCancel, self.m_EditGenre_Cancel_Btn)
        # end wxGlade
        self.__LocalInit__()

    def __set_properties(self):
        # begin wxGlade: MyEditGenreDialog.__set_properties
        self.SetTitle("Edit Genre")
        self.SetSize((300, 131))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyEditGenreDialog.__do_layout
        grid_sizer_11 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_3_copy_1 = wx.FlexGridSizer(1, 5, 0, 0)
        grid_sizer_11.Add(self.m_EditGenre_Text, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 5)
        grid_sizer_11.Add(self.m_EditGenreComboBox, 0, wx.ALL|wx.EXPAND, 5)
        grid_sizer_3_copy_1.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_3_copy_1.Add(self.m_EditGenre_OK_Btn, 0, 0, 0)
        grid_sizer_3_copy_1.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_3_copy_1.Add(self.m_EditGenre_Cancel_Btn, 0, 0, 0)
        grid_sizer_3_copy_1.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_3_copy_1.AddGrowableCol(0)
        grid_sizer_3_copy_1.AddGrowableCol(4)
        grid_sizer_11.Add(grid_sizer_3_copy_1, 1, wx.TOP|wx.BOTTOM|wx.EXPAND, 5)
        self.SetSizer(grid_sizer_11)
        grid_sizer_11.AddGrowableCol(0)
        self.Layout()
        self.Centre()
        # end wxGlade
        
    def __LocalInit__ (self):
        self.m_EditGenre_Text.SetLabel (MyConfig.EditGenreText)
        for Item in MyConfig.Genres:
            self.m_EditGenreComboBox.Append (Item)
        self.m_EditGenreComboBox.SetValue (MyConfig.CurrentGenre)

    def OnEditGenreText(self, event): # wxGlade: MyEditGenreDialog.<event_handler>
#        print "Event handler `OnEditGenreText' not implemented!"
        event.Skip()

    def OnEditGenreCombo(self, event): # wxGlade: MyEditGenreDialog.<event_handler>
#        print "Event handler `OnEditGenreCombo' not implemented!"
        event.Skip()

    def OnGenreOK(self, event): # wxGlade: MyEditGenreDialog.<event_handler>
        MyConfig.EditGenreOK = True
        MyConfig.CurrentGenre = self.m_EditGenreComboBox.GetValue()
        self.Close()
        event.Skip()

    def OnGenreCancel(self, event): # wxGlade: MyEditGenreDialog.<event_handler>
        self.Close()
        event.Skip()

# end of class MyEditGenreDialog


