# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1cvs on Sat Dec 09 16:41:23 2006 from C:\Documents and Settings\rj\workspace\RToolDS\RToolDS.wxg

import wx
import MyConfig

# begin wxGlade: dependencies
# end wxGlade

class MyMissingDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyMissingDialog.__init__
        kwds["style"] = wx.CAPTION|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.m_MissingListBox = wx.ListBox(self, -1, choices=[], style=wx.LB_SINGLE)
        self.m_Missing_OK_Btn = wx.Button(self, -1, "OK")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnOptionsOK, self.m_Missing_OK_Btn)
        # end wxGlade
        self.__LocalInit()
        
    def __set_properties(self):
        # begin wxGlade: MyMissingDialog.__set_properties
        self.SetTitle("Files Missing from Database")
        self.SetSize((400, 300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyMissingDialog.__do_layout
        sizer_7_copy_copy = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_3_copy_copy_copy = wx.FlexGridSizer(1, 3, 0, 0)
        sizer_7_copy_copy.Add(self.m_MissingListBox, 0, wx.EXPAND, 0)
        grid_sizer_3_copy_copy_copy.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_3_copy_copy_copy.Add(self.m_Missing_OK_Btn, 0, wx.TOP|wx.BOTTOM, 5)
        grid_sizer_3_copy_copy_copy.Add((20, 20), 0, wx.EXPAND, 0)
        grid_sizer_3_copy_copy_copy.AddGrowableCol(0)
        grid_sizer_3_copy_copy_copy.AddGrowableCol(2)
        sizer_7_copy_copy.Add(grid_sizer_3_copy_copy_copy, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_7_copy_copy)
        sizer_7_copy_copy.AddGrowableRow(0)
        sizer_7_copy_copy.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def __LocalInit(self):
        self.m_MissingListBox.AppendItems(MyConfig.Missing)
        
    def OnOptionsOK(self, event): # wxGlade: MyMissingDialog.<event_handler>
        self.Close()
        event.Skip()

# end of class MyMissingDialog


